@startuml
actor Alice as A

box "Blockchain" #lightblue
    participant "WETH Channel" as wethch
    participant "ASD Channel" as asdch
    participant "WETH token" as weth
    participant "ASD token" as asd
    participant "Orders" as O
    end box

actor Bob as B

note over weth: **Balances**:\n  50 WETH — Alice\n  10 WETH — WETH Channel
note over asd: **Balances**:\n  80 ASD — Bob\n  20 ASD — ASD Channel

note over wethch: **ch1(WETH)**/round0\n**Alice**\n  10 deposit
note over asdch: **ch2(ASD)**/round0\n**Bob**\n  20 deposit

group Order
    note over B: Sell 5 ASD\nBuy 7 WETH
    B -> O:
    O -> A:
end

group Conditional transfer
    note over A: generate secret Secret\nh = Hash(Secret)
    note over A: **ch1(WETH)**/round1\n**Alice**\n  10 WETH deposit\nPayment(to Bob, h, 7)\nSig(Alice)
    A -> B: send payment
    B -> B: verify
    note over B: **ch2(ASD)**/round1\n**Bob**\n  20 deposit\nPayment(to Alice, h, 5)\nSig(Bob)
    B -> A: send payment
    A -> A: verify
end

group Secret exchange
 A -> B: Secret
 B -> B: verify \n Hash(Secret) = h
end

@enduml
