@startuml
title Two party swap with Sprites
' Assume we have an open channel with sufficient deposit

!include ./two-party-sprites-swap-setup.iuml

group Unconditional transfer (order of messages is interchangeable)
    note over A
        **ch-WETH** @ round 2
        **Alice**
          10 deposit
          -7 credit
        **Bob**
          7 credit
        No Payment
        Sig(Alice)
    end note


    A -> B: send updated channel state

    note over B
        **ch-ASD** @ round 2
        **Alice**
          5 credit
        **Bob**
          20 deposit
          -5 credit
        No Payment
        Sig(Bob)
    end note

    B -> A: send updated channel state
end

group Cooperative withdrawal initiated by Alice
    note over A
        **ch-ASD** @ round 3
        **Alice**
          5 credit
          5 withdrawal
        **Bob**
          20 deposit
          -5 credit
        No Payment
        Sig(Alice)
     end note

    A -> B: I want to withdraw 5 ASD from ch-ASD, like ... right now

    note over B
        **ch-ASD** @ round 3
        **Alice**
          5 credit
          5 withdrawal
        **Bob**
          20 deposit
          -5 credit
        No Payment
        Sig(Bob)
     end note

    B -> A: Yes, Alice, you can withdraw immediately
    A -> asdch: update
    A -> asdch: withdraw
    asdch -> asd: transfer ASD
    asd --> A: 5 ASD
end

note over weth
    **Balances**:
      50 WETH — Alice
      0 WETH — Bob
      10 WETH — WETH Channel
end note

note over asd
    **Balances**:
      5 ASD — Alice
      80 ASD — Bob
      15 ASD — ASD Channel
end note

@enduml
