@startuml
title Two party swap with Sprites
' Assume we have an open channel with sufficient deposit

!include ./two-party-sprites-swap-setup.iuml

group Unconditional transfer (order of messages is interchangeable)
    note over A: **ch-WETH** @ round 2\n**Alice**\n  10 deposit\n  -7 credit\n**Bob**\n  7 credit\nNo Payment\nSig(Alice)

    A -> B: send updated channel state

    note over B #lightgrey: <strike>**ch-ASD** @ round 2</strike>\n**Alice**\n  5 credit\n**Bob**\n  20 deposit\n  -5 credit\nNo Payment\nSig(Bob)

    B -X A: does not send updated channel state
end


group Bob tries to take out his WETH
    B -> wethch: trigger a dispute for ch-WETH
    wethch -> A: LogTrigger
    B -> wethch: update to ch-WETH @ round 2

    A -> asdch: trigger a dispute for ch-ASD
    A -> pm: register(Secret)
    A -> wethch: update to ch-ASD @ round 1

    ... wait for timeouts ...

    A -> asdch: finalize
    asdch -> pm: revealed(h)
    note over asdch: Secret revealed in time.\nCredit payment to Alice.

    A -> asdch: widthdraw
    asdch --> asd: transfer 5 ASD to Alice
    B -> asdch: widthdraw
    asdch --> asd: transfer 15 ASD to Bob

    B -> wethch: finalize
    B -> wethch: withdraw
    wethch --> weth: transfer 7 WETH to Bob

    A -> wethch: withdraw
    wethch --> weth: transfer 3 WETH to Alice
end

note over weth: **Balances**:\n  53 WETH — Alice\n  7 WETH — Bob\n  0 WETH — WETH Channel
note over asd: **Balances**:\n  5 ASD — Alice\n  95 ASD — Bob\n  0 ASD — ASD Channel


@enduml
