@startuml
title Two party swap with Sprites
' Assume we have an open channel with sufficient deposit

!include ./two-party-sprites-swap-setup.iuml

group Unconditional transfer (order of messages is interchangeable)
    note over A
        **ch-WETH** @ round 2
        **Alice**
          10 deposit
          -7 credit
        **Bob**
          7 credit
        No Payment
        Sig(Alice)
    end note

    A -> B: send updated channel state

    note over B #lightgrey
        <strike>**ch-ASD** @ round 2</strike>
        **Alice**
          5 credit
        **Bob**
          20 deposit
          -5 credit
        No Payment
        Sig(Bob)
    end note

    B -X A: does not send updated channel state
end

group Bob tries to take out his WETH
    B -> wethch: trigger a dispute for ch-WETH
    wethch -> A: LogTrigger
    B -> wethch: update to ch-WETH @ round 2

    A -> asdch: trigger a dispute for ch-ASD
    A -> pm: register(Secret)
    A -> wethch: update to ch-ASD @ round 1

    ... wait for timeouts ...

    A -> asdch: finalize
    asdch -> pm: revealed(h)

    note over asdch
        Secret revealed in time.
        Credit payment to Alice.
    end note

    A -> asdch: withdraw
    asdch --> asd: transfer 5 ASD to Alice
    B -> asdch: withdraw
    asdch --> asd: transfer 15 ASD to Bob

    B -> wethch: finalize
    B -> wethch: withdraw
    wethch --> weth: transfer 7 WETH to Bob

    A -> wethch: withdraw
    wethch --> weth: transfer 3 WETH to Alice
end

note over weth
    **Balances**:
      53 WETH — Alice
      7 WETH — Bob
      0 WETH — WETH Channel
end note

note over asd
    **Balances**:
      5 ASD — Alice
      95 ASD — Bob
      0 ASD — ASD Channel
end note

@enduml
