@startuml
!pragma teoz true

title Two party swap via trusted DEX
' Assume we have an open channel with sufficient deposit
actor Alice as A

box "Blockchain" #lightblue
    participant "WETH Channel\nAlice-DEX" as wethalice
    participant "ASD Channel\nAlice-DEX" as asdalice
    participant "DEX" as dex
    participant "WETH Channel\nBob-DEX" as wethbob
    participant "ASD Channel\nBob-DEX" as asdbob
    ' participant "WETH token" as weth
    ' participant "ASD token" as asd
    participant "Orders" as O
end box

actor Bob as B

'note over weth
'    **Balances**:
'      50 Alice
'      10 Alice-Dex
'      100 Bob-Dex
'end note
'
'/ note over asd
'    **Balances**:
'      80 Bob
'      20 Bob-Dex
'      10 Alice-Dex
'end note

note over wethalice
    round 0
    **Alice**
      10 deposit
end note

/ note over asdalice
    round 0
    **DEX**
      10 deposit
end note

/ note over wethbob
    round 0
    **DEX**
      100 deposit
end note

/ note over asdbob
    round 0
    **Bob**
      20 deposit
end note


group Order
    note over B: Sell 5 ASD\nBuy 7 WETH
    B -> O:
    O -> A:
end

group Unconditional transfer to DEX

    A -> dex: 7 WETH
    B -> dex: 5 ASD

    note over wethalice
        round 1
        **Alice**
          -7 credit
        **DEX**
          7 credit
    end note

    / note over asdbob
        round 1
        **Bob**
          -5 credit
        **DEX**
           5 credit
    end note
end

group Unconditional transfer to Users

    dex -> B: 7 WETH
    dex -> A: 5 ASD

    note over wethbob
        round 1
        **Bob**
          7 credit
        **DEX**
          -7 credit
    end note

    / note over asdalice
        round 1
        **Alice**
          5 credit
        **DEX**
          -5 credit
    end note
end

@enduml
