@startuml
actor Alice as A

box "Blockchain" #lightblue
    participant "WETH Channel" as wethch
    participant "ASD Channel" as asdch
    participant "WETH token" as weth
    participant "ASD token" as asd
    participant "Orders" as O
    participant "Preimage\nManager" as pm
end box

actor Bob as B

note over weth
    **Balances**:
      50 WETH — Alice
      10 WETH — WETH Channel
end note

/ note over asd
    **Balances**:
      80 ASD — Bob
      20 ASD — ASD Channel
end note

/ note over wethch
    **ch-WETH** @ round 0
    **Alice**
      10 deposit
end note

/ note over asdch
    **ch-ASD** @ round 0
    **Bob**
      20 deposit
end note

group Order
    note over B
        Sell 5 ASD
        Buy 7 WETH
    end note

    B -> O:
    O -> A:
end

group Conditional transfer
    note over A
        generate secret Secret
        h = Hash(Secret)
    end note

    note over A
        **ch-WETH** @ round 1
        **Alice**
          10 WETH deposit
        Payment(to Bob, h, 7)
        Sig(Alice)
    end note

    A -> B: send payment
    B -> B: verify

    note over B
        **ch-ASD** @ round 1
        **Bob**
          20 deposit
        Payment(to Alice, h, 5)
        Sig(Bob)
    end note

    B -> A: send payment
    A -> A: verify
end

group Secret exchange
    A -> B: Secret
    B -> B: verify\n  Hash(Secret) = h
end

@enduml
