@startuml
actor Alice as A

box "Blockchain" #lightblue
    participant "Channel registry" as reg
    participant "WETH token" as weth
end box

actor Bob as B

note over weth: Balances:\n  Alice: 50\n  Bob: 80\n  reg: 0
note over reg: current channel = 0
A -> reg: Open channel
note over reg: current channel = 1
note over reg: **Alice**\n  0 Deposit\n  0 Credit\n  0 Withdrawal\n**Bob**\n  0 Deposit\n  0 Credit\n  0 Withdrawal
reg -> reg: LogChannel(\n  ID: 1,\n  left: Alice,\n  right: Bob)
reg --> A: Channel ID: 1
reg --> B: Channel ID: 1
...
note over A: **Alice**\n  10 Deposit
A -> reg: Deposit 10 WETH
reg -> weth: transferFrom(\n  Alice, itself, 10 WETH)
note over weth: Balances:\n  Alice: 40\n  Bob: 80\n  reg: 10
reg --> B: Deposit(Alice, cID: 1, 10)
note over B: **Alice**\n  10 Deposit
...
note over A: **Alice**\n  10 Deposit\n -7 Credit\n**Bob**\n  7 Credit
A -> B: send(7, over cID 1)
note over B: **Alice**\n  10 Deposit\n -7 Credit\n**Bob**\n  7 Credit

@enduml
