@startuml
actor Alice as A

box "Blockchain" #lightblue
    participant "Channel Registry" as reg
    participant "WETH token" as weth
end box

actor Bob as B

note over weth
    **Balances**:
      50 — Alice
      80 — Bob
      0 — Ch. Reg.
end note

note over reg
    channel count: 0
end note


group Open channel
    A -> reg: Open channel

    note over reg
        **chID:** 0
        **Alice**
          0 Deposit
          0 Credit
          0 Withdrawal
        **Bob**
          0 Deposit
          0 Credit
          0 Withdrawal
    end note

    reg -> reg: LogChannel(\n  ID: 0,\n  left: Alice,\n  right: Bob)

    note over reg: channel count: 1

    reg --> A: Channel ID: 0
    reg --> B: Channel ID: 0
end

group Deposit
    note over A
        **Alice**
          10 Deposit
    end note

    A -> reg: Deposit 10 WETH

    note over reg
        **Alice**
          10 Deposit
    end note

    reg -> weth: transferFrom(\n  Alice, itself, 10 WETH)

    note over weth
        **Balances**:
          40 — Alice
          80 — Bob
          10 — Ch. Reg.
    end note

    reg --> B: Deposit(Alice, chID: 0, 10)

    note over B
        **Alice**
          10 Deposit
    end note
end

group Transfer
    note over A
        **Alice**
          10 Deposit
          -7 Credit
        **Bob**
          7 Credit
    end note

    A -> B: send(7, over chID 1)

    note over B
        **Alice**
          10 Deposit
          -7 Credit
        **Bob**
          7 Credit
    end note
end

group Cooperative Settle by Alice
    note right A: Balance = Deposit + Credit - Withdraw

    note over A
        **Alice**
          -7 Credit
          3 Withdrawal
        **Bob**
          7 Credit
          7 Withdrawal
    end note

    A -> B: send signed channel state
    B -> reg: update(channel)

    note over reg
        **Alice**
          10 Deposit
          -7 Credit
          3 Withdrawal
        **Bob**
          0 Deposit
          7 Credit
          7 Withdrawal
    end note


    A -> reg: Withdraw
    reg -> weth: transfer 3 WETH to Alice
    note over weth
        **Balances**:
          43 — Alice
          80 — Bob
          7 — Ch. Reg.
    end note

    B -> reg: Withdraw
    reg -> weth: transfer 7 WETH to Bob

    note over weth
        **Balances**:
          43 — Alice
          87 — Bob
          0 — Ch. Reg.
    end note
end

@enduml
